### PR TITLE
ff2r_default_abilities: Allow specifying duration of a weapon

### PR DESCRIPTION
**Pull request by naydef**
Fixes https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/issues/118

### CODE REVIEW

**Comment by naydef** [comment]
SM 1.12 compiler broken, I guess.

**Comment by naydef** [comment]
This will need further improvements:
1. If the spawned weapon doesn't have a weapon occupying the same slot on spawn, then player won't get active weapon.
2. There is know issue, where removing spinning minigun will cause the player to move slowly (also i've heard about crashes when doing so...)

**Comment by Batfoxkid** [comment]
If going to make weapon restores available after the duration wears off, I recommend
1. Not removing the slot for the new weapon to occupy
2. Removing only the weapon specifically rather then the entire slot when it wears off

**Comment by naydef** [comment]
Hm, ok. Then I guess `TF2_RemoveWeaponSlot` can be replaced with `AcceptEntityInput` in `Rage_NewWeapon`, too.

**Comment by naydef** [comment]
Honestly I'd have been nice If those functions were available for use by including files instead of copying those every plugin needs. Otherwise a lot of duplicating happens (same for GetSectionType, GetKillsOfCosmeticRank, etc...).

Maybe I can try including this file anyway.

**Pull request closed without merging**
